version: "3.5"
services:
  web_sjohaug:
    build:
      context: .
      dockerfile: dockerfile.production
    ports:
      - "11000:80"
    environment:
      - CONTAINER=true

networks:
    default:
        name: stella_network
