version: "3.5"
services:
  web_sjohaug:
    image: docker.pkg.github.com/joakimsjo/sjoha.ug/web:latest
    ports:
      - "11000:80"
    environment:
      - CONTAINER=true

networks:
  default:
    name: stella_network
