name: Build and push docker image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: joakimsjo
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: joakimsjo/sjoha.ug/web
          registry: docker.pkg.github.com
          dockerfile: .docker/dockerfile.production
          tag_with_sha: true
          tag_with_ref: true
