name: Build and deploy docker image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and tag docker image
        run: docker build . -f .docker/dockerfile.production -t docker.pkg.github.com/joakimsjo/sjoha.ug/web:latest
      - name: Docker login
        run: docker login -u joakimsjo -p "${DOCKER_PASSWORD}" docker.pkg.github.com
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image
        run: docker push docker.pkg.github.com/joakimsjo/sjoha.ug/web:latest
      - name: Restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.private_key }}
          script: |
            ${{ secrets.rebuild_container }}
